[package]
name = "ilo4-unlock"
version = "1.0.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
reqwest = "0.12.2"
sha1 = "0.10.6"
tokio = { version = "1.37.0", features = [ "full" ] }
xml-rs = "0.8.19"
# example = "1.0.0"
